[package]
name = "music"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
dirs = "6.0.0"
image = "0.25.10"
lofty = "0.24.0"
lru = "0.18.1"
ratatui = "0.30.0"
ratatui-image = "11.0.4"
redb = "4.1.0"
rodio = { version = "0.22.2", features = ["symphonia-all"] }
serde = { version = "1.0.228", features = ["derive"] }
symphonia = { version = "0.6.0", features = ["all-codecs", "all-formats"] }
toml = "1.1.2"
tui = "0.19.0"
wincode = { version = "0.6.0", features = ["derive"] } 
